server:
  port: 7000
  servlet:
    context-path: /generate
spring:
  datasource:
      url: jdbc:mysql://120.77.209.219:3306/gen_code?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
      username: gen_code
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      platform: mysql
      type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      #开启MVC thymeleaf 视图解析
      enabled: true
      encoding: utf-8
      mode: HTML5
      prefix: classpath:/templates/
      suffix: .html

#mybatis \u548C \u901A\u7528Mapper
mybatis:
  type-aliases-package: com.liuzw.generate.model
  mapper-locations: classpath:mapper/*.xml


#\u5206\u9875
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count = countSql
